[package]
name = "project1"
version = "0.1.0"
authors = ["Kurtil <gaetan.lagier@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"